import React, {Component} from 'react';
import './Problems.css'

class Problem2 extends Component {
  state = {showSolution:false}

  showSolutionHandler = () => {
    this.setState({showSolution:!this.state.showSolution})
  }

  fibonacciSum = (terms) => {
      //initial terms
      let fib = [1,2];

      for( let i=2 ; i<=terms ; i++ ) {
          //fibonacci number
          let num = fib[i-1] + fib[i-2];
          //added number to array
          if( num <= 4000000){
            fib.push(num);
          }
      }
      //removed odd fibonaccis
      const evens = fib.filter(num => num % 2 === 0);
      //reduced array of odds to a sum
      const sum = evens.reduce((a,b) => a + b);
      return sum;
  }

  render() {
    let solution = null;
    if(this.state.showSolution) {
      solution = <Solution />
    }

    return (
      <div className="Problem">
        <h2>Problem 2: Even Fibonacci numbers (Solved)</h2>
        <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
        <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
        <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
        <h4>even sum with 10 terms: {this.fibonacciSum(10)}</h4>
        <h4>even sum with 20 terms: {this.fibonacciSum(20)}</h4>
        <h4>even sum with 30 terms: {this.fibonacciSum(30)}</h4>
        <h3>even sum with 31 terms: {this.fibonacciSum(31)}</h3>
        <button className="Button" onClick={() => this.showSolutionHandler()}>{this.state.showSolution ? 'Hide solution notes' : 'Show solution notes'}</button>
        {solution}
      </div>
    );
  }
}

const Solution = () => {
  return (
    <div>
      <p>Initialized a fibonacci array with [1,2] as starting entries</p>
      <p>Used a for loop over fixed number of terms</p>
      <p>Inside the loop created local variable adding two previous fibonacci numbers</p>
      <p>Pushed all fibonacci numbers to the array if they were less than 4000000</p>
      <p>Filtered the fibonacci array down to only even numbers</p>
      <p>Added all numbers in the resulting array using reduce</p>
    </div>
  );
}


export default Problem2;
